/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#191c22',
        'surface-container': '#1d2026',
        surface: '#10131a',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#b8c9d3',
        'secondary-container': '#3b4b53',
        'on-secondary-container': '#aabbc5',
        'on-tertiary-container': '#eeb300',
        'on-background': '#e1e2eb',
        'surface-variant': '#32353c',
        'on-secondary-fixed': '#0d1e25',
        'on-surface': '#e1e2eb',
        'on-secondary': '#23333a',
        'primary-container': '#004d89',
        'outline-variant': '#434652',
        'primary-fixed': '#d3e4ff',
        'on-primary': '#00315b',
        'on-secondary-fixed-variant': '#394951',
        'on-tertiary-fixed': '#261a00',
        'on-error': '#690005',
        'surface-container-highest': '#32353c',
        primary: '#a2c9ff',
        'on-primary-container': '#8ebfff',
        'inverse-primary': '#0060a8',
        'inverse-surface': '#e1e2eb',
        'inverse-on-surface': '#2e3037',
        'primary-fixed-dim': '#a2c9ff',
        outline: '#8d909d',
        'tertiary-fixed': '#ffdf9e',
        background: '#10131a',
        'surface-bright': '#363940',
        'surface-tint': '#a2c9ff',
        'on-surface-variant': '#c3c6d4',
        error: '#ffb4ab',
        'on-tertiary-fixed-variant': '#5b4300',
        'tertiary-fixed-dim': '#fabd00',
        'on-primary-fixed-variant': '#004881',
        'secondary-fixed': '#d4e5ef',
        'surface-container-high': '#272a31',
        'tertiary-container': '#614800',
        secondary: '#b8c9d3',
        'on-tertiary': '#3f2e00',
        'surface-container-lowest': '#0b0e14',
        tertiary: '#fabd00',
        'surface-dim': '#10131a',
        'on-error-container': '#ffdad6',
        'on-primary-fixed': '#001c38',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Manrope', 'system-ui', 'sans-serif'],
        label: ['Manrope', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
